# Generated by Django 4.2.2 on 2023-06-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
    ]
